import lang_javascript from 'highlight.js/lib/languages/javascript';
import lang_json from 'highlight.js/lib/languages/json';
import lang_xml from 'highlight.js/lib/languages/xml';
import lang_html from 'highlight.js/lib/languages/xml';
import lang_css from 'highlight.js/lib/languages/css';
import lang_typescript from 'highlight.js/lib/languages/typescript';
import lang_bash from 'highlight.js/lib/languages/bash';
import lang_yaml from 'highlight.js/lib/languages/yaml';
import lang_markdown from 'highlight.js/lib/languages/markdown';
import lang_php from 'highlight.js/lib/languages/php';
import lang_python from 'highlight.js/lib/languages/python';
import lang_java from 'highlight.js/lib/languages/java';
import lang_ruby from 'highlight.js/lib/languages/ruby';
import lang_rust from 'highlight.js/lib/languages/rust';
import lang_csharp from 'highlight.js/lib/languages/csharp';
import lang_swift from 'highlight.js/lib/languages/swift';
import lang_kotlin from 'highlight.js/lib/languages/kotlin';
import lang_perl from 'highlight.js/lib/languages/perl';
import lang_lua from 'highlight.js/lib/languages/lua';
import lang_sql from 'highlight.js/lib/languages/sql';
import lang_go from 'highlight.js/lib/languages/go';

import hljs from 'highlight.js';
hljs.registerLanguage('javascript', lang_javascript);
hljs.registerLanguage('json', lang_json);
hljs.registerLanguage('xml', lang_xml);
hljs.registerLanguage('html', lang_html);
hljs.registerLanguage('css', lang_css);
hljs.registerLanguage('typescript', lang_typescript);
hljs.registerLanguage('bash', lang_bash);
hljs.registerLanguage('yaml', lang_yaml);
hljs.registerLanguage('markdown', lang_markdown);
hljs.registerLanguage('php', lang_php);
hljs.registerLanguage('python', lang_python);
hljs.registerLanguage('java', lang_java);
hljs.registerLanguage('ruby', lang_ruby);
hljs.registerLanguage('rust', lang_rust);
hljs.registerLanguage('csharp', lang_csharp);
hljs.registerLanguage('swift', lang_swift);
hljs.registerLanguage('kotlin', lang_kotlin);
hljs.registerLanguage('perl', lang_perl);
hljs.registerLanguage('lua', lang_lua);
hljs.registerLanguage('sql', lang_sql);
hljs.registerLanguage('go', lang_go);